import { Mongify, type StoredDocument } from "../dist/mongify.js";

interface User {
  name: string;
  age: number;
  active?: boolean;
  createdAt: Date;
}

const database = new Mongify({ database_name: "typed-database" });
const users = database.getCollection<User>("users");

async function verifyGenericCollection(): Promise<void> {
  await users.insert({
    name: "Pamela",
    age: 37,
    createdAt: new Date("2026-08-16T00:00:00Z"),
  });
  await users.insertMany([
    { name: "Alice", age: 30, createdAt: new Date() },
  ]);

  // @ts-expect-error age is required by User
  await users.insert({ name: "Missing age", createdAt: new Date() });
  // @ts-expect-error _id is generated by Mongify
  await users.insert({ _id: "manual", name: "Invalid", age: 1, createdAt: new Date() });

  const result: StoredDocument<User>[] = await users.find(
    { age: { $gte: 18 } },
    { sort: { age: -1 }, projection: { name: 1 } },
  );
  const first = await users.findOne({ name: "Pamela" });
  if (first) {
    const id: string = first._id;
    const age: number = first.age;
    void id;
    void age;
  }

  await users.update({ name: "Pamela" }, { active: true });
  await users.delete({ createdAt: { $lt: new Date() } });
  await users.createIndex(["name", "age"]);

  // @ts-expect-error age queries require numbers
  await users.find({ age: { $gte: "18" } });
  // @ts-expect-error unknown is not a User field
  await users.update({ name: "Pamela" }, { unknown: true });
  // @ts-expect-error index fields must belong to the stored model
  await users.createIndex("unknown");
  // @ts-expect-error sort direction must be 1 or -1
  await users.find({}, { sort: { age: 0 } });

  void result;
}

void verifyGenericCollection;
